name: TpaForm
version: '${project.version}'
main: ltd.rymc.form.tpa.TpaForm
api-version: 1.13
depend: [ floodgate ]
softdepend:  [ XTLib ]
authors:
  - RENaa_FD
  - xiantiao
description: Tpa Form菜单支持
website: https://rymc.ltd/
folia-supported: true
permissions:
  tpaform.reload:
    description: "TpaForm重载权限"
    default: op