name: TpaForm
version: '${project.version}'
main: ltd.rymc.form.tpa.TpaForm
api-version: 1.13
depend: [ floodgate ]
authors: [ RENaa_FD ]
description: Tpa Form菜单支持
website: https://rymc.ltd/
folia-supported: true
permissions:
  tpaform.reload:
    description: "TpaForm重载权限"
    default: op